### ISSUE TITLE
Not able to add to asp.net core 1.0 rc2

### ISSUE THREAD

**Issue by srinivasnarula** [aliencube/AppForSharePointOnlineWebToolkit.Compiled#1]
I am using asp.net core rc2
    "Microsoft.NETCore.App": {
      "version": "1.0.0-rc2-3002702",
      "type": "platform"
    }.

When I run Install-Package AppForSharePointOnlineWebToolkit.Compiled -Version 3.1.2.18 or the latest version Install-Package AppForSharePointOnlineWebToolkit.Compiled -Version 3.1.4 on my solution.
I am getting below error.

**Package AppForSharePointOnlineWebToolkit.Compiled 3.1.2.18 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package AppForSharePointOnlineWebToolkit.Compiled 3.1.2.18 supports: net45 (.NETFramework,Version=v4.5)
    One or more packages are incompatible with .NETCoreApp,Version=v1.0.**

What is the work around for this issue?
Whether latest nuget package supports asp.net rc2?

Advance Thanks!!

**Comment by srinivasnarula** [comment]
Above issue is resolved. When I run the nuget command in webapplication (.NET Core), it is not package name is not getting saved at write location. It was failing. 

We need to manually, move the package to dependencies section.

"dependencies": {
    **"AppForSharePointOnlineWebToolkit.Compiled": "3.1.4.25",**
    "Microsoft.AspNetCore.Authentication.Cookies": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Diagnostics": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Mvc": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.0.0-preview1-final",
      "type": "build"
    }

**Comment by srinivasnarula** [comment]
Please ignore this issue. It is resolved.

**Comment by justinyoo** [comment]
@narulasrinivas Glad to hear that you sorted out the issue. :-)
