### ISSUE TITLE
Not able to call ClientContextHelper in aspnet core - controller method

### ISSUE THREAD

**Issue by srinivasnarula** [aliencube/AppForSharePointOnlineWebToolkit.Compiled#2]
When I call ClientContextHelper in a controller method, as mentioned below. It is failing.

```
 public async Task<IActionResult> Index()
        {
            var helper = new ClientContextHelper();
            using (var context = helper.CreateAppOnlyClientContext("https://srinisp.sharepoint.com/sites/test/apps"))
            {

            }        
        }

```

An unhandled exception occurred while processing the request.

CryptographicException: The system cannot find the path specified.
System.Security.Cryptography.CryptographicException.ThrowCryptographicException(Int32 hr)

TypeInitializationException: The type initializer for 'AppForSharePointOnlineWebToolkit.TokenHelper' threw an exception.
AppForSharePointOnlineWebToolkit.TokenHelper.GetAppOnlyAccessToken(String targetPrincipalName, String targetHost, String targetRealm)

**Do we need to add any other files apart from package and spoconfig.json ??**

**Comment by justinyoo** [comment]
@narulasrinivas Thanks for raising this issue. Have you tried to put `spoconfig.json` under the `wwwroot` folder? In RC1, `spoconfig.json` should be copied under the `wwwroot` to get it working, but not sure on RC2.

**Comment by srinivasnarula** [comment]
Moved spoconfig.json to wwwroot, still getting error:

An unhandled exception occurred while processing the request.

> FileNotFoundException: spoconfig.json not found
> AppForSharePointOnlineWebToolkit.Configs.SpoConfigManager.Load()
> 
> TypeInitializationException: The type initializer for 'AppForSharePointOnlineWebToolkit.TokenHelper' threw an exception.
> AppForSharePointOnlineWebToolkit.TokenHelper.GetAppOnlyAccessToken(String targetPrincipalName, String targetHost, String targetRealm)

**Comment by srinivasnarula** [comment]
Please share link to download the working sample of rc1.

**Comment by justinyoo** [comment]
@narulasrinivas I've put sample RC1 and RC2 web applications. Please pull the latest copy and run those samples. Make sure that you've already got an Office 365 tenant and Client Id & Secret for AppOnly mode.

Also make sure that this library only works on .NET framework (`dnx451` on RC1 and `net461` on RC2), not .NET Core (`dnxcore50` on RC1 and `netcoreapp1.0` on RC2).

**Comment by justinyoo** [comment]
@narulasrinivas If you have any issue, please open another one. I'll close it now.
